package main

import (
	"database/sql"
	"database/sql/driver"
	"errors"
	"log"
	//"strconv"
	"strings"

	_ "github.com/lib/pq"
)

type SQLDescriber interface {
	Columns() []any
	ColumnsString() string
	TableName() string
}

// type Column = sql.Scanner

// type Expenditure struct {
// 	Id           *int     `json:"id"`
// 	UserId       *int     `json:"userId"`
// 	CategoryId   *sql.Null[int]    `json:"categoryId"`
// 	Value        *float32 `json:"value"`
// 	Description  *string  `json:"description"`
// 	DateOccurred *string  `json:"dateOccurred"`
// 	CreateDate   *sql.Null[string]  `json:"createDate"`
// 	ModifiedDate *sql.Null[string]  `json:"modifiedDate"`
// }

type Expenditure struct {
	Id           *NotNull[int]     `json:"id"`
	UserId       *NotNull[int]     `json:"userId"`
	CategoryId   *sql.Null[int]    `json:"categoryId"`
	Value        *NotNull[float32] `json:"value"`
	Description  *NotNull[string]  `json:"description"`
	DateOccurred *NotNull[string]  `json:"dateOccurred"`
	CreateDate   *sql.Null[string] `json:"createDate"`
	ModifiedDate *sql.Null[string] `json:"modifiedDate"`
}

// `NotNull[T]` implements `sql.Scanner`
// `driver.Value` is just `any`, but should be certain pointer types.
// https://pkg.go.dev/database/sql/driver#Value
type NotNull[T driver.Value] struct {
	V     T
	Valid bool
}

func (nn *NotNull[T]) Scan(value any) error {

	if value == nil {
		return errors.New("nil value for NotNull Column")
	}

	nullable := &sql.Null[T]{nn.V,true}
	return nullable.Scan(value)
}

func (nn NotNull[T]) Value() (driver.Value, error) {
	nullable := sql.Null[T]{nn.V,true}
	return nullable.Value()
}

// func (n Null[T]) Value() (driver.Value, error)

// id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
// user_id int NOT NULL,
// category_id int,
// value decimal NOT NULL,
// description text NOT NULL,
// date_occurred timestamp NOT NULL,
// create_date timestamp default now(),
// modified_date timestamp default now()

func (e Expenditure) ColumnNames() []string {
	columns := []string{
		"exp.id",
		"exp.user_id",
		"exp.category_id",
		"exp.value",
		"exp.description",
		"exp.date_occurred",
		"exp.create_date",
		"exp.modified_date",
	}
	return columns
}

func (e Expenditure) ColumnsString() string {
	return strings.Join(e.ColumnNames(), ",")
}

func ZeroedExpenditure() Expenditure {
	e := Expenditure{}

	e.Id = &NotNull[int]{0, true}
	e.UserId = &NotNull[int]{0, true}
	e.CategoryId = &sql.Null[int]{0, false}
	var floatZero float32 = 0.0
	e.Value = &NotNull[float32]{floatZero, true}
	e.Description = &NotNull[string]{"", true}
	e.DateOccurred = &NotNull[string]{"", true}
	e.CreateDate = &sql.Null[string]{"", false}
	e.ModifiedDate = &sql.Null[string]{"", false}

	return e
}

func (e Expenditure) Columns() []any {
	return []any{
		e.Id,
		e.UserId,
		e.CategoryId,
		e.Value,
		e.Description,
		e.DateOccurred,
		e.CreateDate,
		e.ModifiedDate,
	}
}

func (e Expenditure) ColumnValues() []any {
	return []any{
		*e.Id,
		*e.UserId,
		*e.CategoryId,
		*e.Value,
		*e.Description,
		*e.DateOccurred,
		*e.CreateDate,
		*e.ModifiedDate,
	}
}

func (e Expenditure) Print() {
	columnNames := e.ColumnNames()
	for index, value := range e.ColumnValues() {

		log.Println(columnNames[index]+": ", value)
	}
}

func (e Expenditure) TableName() string {
	return "expenditure exp"
}

// connectionString -> "user=postgres password=postgres dbname=postgres sslmode=disable"
// func BuildPostgresClient(connectionString string) (PGClient, error) {

// 	db, err := sql.Open("postgres", connectionString)
// 	if err != nil {

// 		log.Println("ERROR opening postgres connection with github.com/neurocollective/go_utils.BuildPostgresClient() ->")
// 		log.Println(err.Error())

// 		return nil, err
// 	}

// 	return db, nil
// }

func Select[S SQLDescriber](client *sql.DB, query string, args []any) ([]S, error) {

	var empty []S

	rows, queryError := client.Query(query, args...)

	if queryError != nil {
		return empty, queryError
	}

	return ReceiveRows[S](rows)
}

func InsertExpenditure(client *sql.DB, e Expenditure) error {
	queryString := "insert into expenditure values (nextval('expenditure_id_seq'), $1, $2, $3, $4, now(), now(), now());"

	// args := e.Columns()

	args := []any{
		e.UserId.V,
		nil,
		e.Value.V,
		e.Description.V,
	}

	_, err := client.Query(queryString, args...)

	if err != nil {
		return err
	}
	return nil
}

func ReceiveExpenditures(rows *sql.Rows) ([]Expenditure, error) {
	var empty []Expenditure

	capacity := 100

	rowArray := make([]Expenditure, capacity, capacity)
	var index int

	// resultsExist := rows.NextResultSet()

	// if !resultsExist {
	// 	err := rows.Err()

	// 	if err != nil {
	// 		log.Println("error getting rows:", err)
	// 		return empty, err
	// 	}
	// 	log.Println("no results!")
	// 	return empty, nil
	// }

	for rows.Next() {

		receiver := ZeroedExpenditure()

		if index == capacity-1 {
			capacity += 100
			newRowArray := make([]Expenditure, 0, capacity)

			copy(newRowArray, rowArray)
			rowArray = newRowArray
		}

		values := receiver.Columns()

		log.Println("columns:", values)

		err := rows.Scan(values...)

		if err != nil {
			log.Println("scanError", err.Error())
			return empty, err
		}

		rowArray[index] = receiver
		index++
	}

	return rowArray[:index], nil
}

func ReceiveRows[T SQLDescriber](rows *sql.Rows) ([]T, error) {

	var empty []T

	capacity := 100

	rowArray := make([]T, capacity, capacity)
	var index int

	for rows.Next() {

		var receiver T

		if index == capacity-1 {
			capacity += 100
			newRowArray := make([]T, 0, capacity)

			copy(newRowArray, rowArray)
			rowArray = newRowArray
		}

		values := receiver.Columns()

		err := rows.Scan(values...)

		if err != nil {
			log.Println("scanError", err.Error())
			return empty, err
		}

		rowArray[index] = receiver
		index++
	}

	// getNextRowError := rows.Err()

	// if getNextRowError != nil {
	// 	log.Println("error getting next row:", getNextRowError.Error())
	// 	return empty, getNextRowError
	// }

	return rowArray[:index], nil
}
